name: 'cypress-test-sumary'
description: 'Cypress test summary table'
author: Layer5
inputs:
  jsonInput:  # id of input
    description: 'Test output in json'
    required: false
    default: '{}'
  jsonArtifact:
    description: "JSON artifact that can be optionally used as a json file to pick"
    required: false
outputs:
  mardownResult: # id of output
    description: 'The markdown result'
runs:
  using: 'node16'
  main: 'dist/index.js'
